# Select image from https://hub.docker.com/_/php/
image: php:7.0-cli

# Select what we should cache
cache:
  paths:
  - vendor/

before_script:
# Install git, the php image doesn't have installed
- apt-get update -yqq
- apt-get install git -yqq
# Install the vcs.missouri.edu cert
- sudo apt-get install gnutls-bin 
- gnutls-cli --print-cert vcs.missouri.edu </dev/null| sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > vcs.missouri.edu.crt
- sudo cp myserver.crt /usr/local/share/ca-certificates/vcs.missouri.edu.crt
- sudo update-ca-certificates

# Install composer
- curl -sS https://getcomposer.org/installer | php

# Install all project dependencies
- php composer.phar install

test:php7:
  image: php:7
  script:
  - vendor/bin/phpunit --coverage-text

